#!/bin/bash

echo "🔧 Script para criar repositório no GitHub"
echo "=========================================="
echo ""
echo "📋 Passos para criar o repositório:"
echo ""
echo "1. Acesse: https://github.com/new"
echo "2. Nome do repositório: site-temvenda"
echo "3. Descrição: Site TEM VENDA - Sistema de captura de leads"
echo "4. Marque como 'Public' ou 'Private'"
echo "5. NÃO marque 'Add README' (já temos arquivos)"
echo "6. Clique em 'Create repository'"
echo ""
echo "7. Após criar, execute:"
echo "   git push origin main"
echo ""
echo "🔗 Ou use o GitHub CLI (se instalado):"
echo "   gh repo create site-temvenda --public --description 'Site TEM VENDA - Sistema de captura de leads'"
echo ""
echo "📁 Arquivos prontos para upload:"
echo "- Sistema completo de captura de leads Instagram"
echo "- Admin para gerenciar textos e PDF"
echo "- Integração com Supabase e EmailJS"
echo "- Funil de vendas com drag & drop"
echo "- Upload de PDF e imagens"
echo ""
echo "✅ Após criar o repositório, execute:"
echo "   ./deploy-github-infinityfree.sh"
